name: persist_notifier
description: A ValueNotifier designed for defining settings and providing a solution with a default value and notification system.
version: 1.1.0
repository: https://github.com/voidari/flutter/tree/main/persist_notifier
issue_tracker: https://github.com/voidari/flutter/labels/persist%20notifier

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences_platform_interface: ^2.0.0